# This is a basic workflow to help you get started with Actions

name: Tag for Deployment
on:

  workflow_dispatch:
    inputs:
      market:
        type: choice
        description: "Please select a market for production deployment"
        options:
        - all
        - singsaver
        - moneyhero
        - money101
        - comparehero
        - moneyguru
        - moneymax
        required: true
        default: "all"
      ack:
        type: boolean
        description: "Confirm?"
        required: true

jobs:
  execute:
    if: ${{ github.ref == 'refs/heads/master' && github.event.inputs.ack == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Preperation
        run: echo market - ${{ github.event.inputs.market }} and confirm - ${{ github.event.inputs.ack }}
      - name: CreateTag
        run: |
          createTag () {
            local market=$1
            local version=`git rev-parse --short HEAD`
            local tag=deploy-$market-$version

            echo 'Create tag:' $tag
            git tag $tag
            git push origin $tag
          }
          case ${{ github.event.inputs.market }} in
            singsaver|moneyhero|money101|comparehero|moneyguru|moneymax)
              createTag ${{ github.event.inputs.market }}
              ;;
            all)
              createTag singsaver
              createTag moneyhero
              createTag money101
              createTag comparehero
              createTag moneymax
              createTag moneyguru
              ;;
          esac