name: CI

on:
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: True or False
        required: true
      choice:
        type: choice
        required: true
        description: Make a choice
        options:
        - foo
        - bar
        - baz
      commit:
        required: true
        type: string
        description: Enter commit hash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout commit
        with:
          ref: 5c8b9e8

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "commit is ${{ github.event.inputs.commit }}"