name: CI

on:
  workflow_dispatch:
    inputs:
      singsaver:
        required: false
        type: boolean
        description: singsaver
      moneyhero:
        required: false
        type: boolean
        description: moneyhero
      money101:
        required: false
        type: boolean
        description: money101
      comparehero:
        required: false
        type: boolean
        description: comparehero
      moneyguru:
        required: false
        type: boolean
        description: moneyguru
      moneymax:
        required: false
        type: boolean
        description: moneymax
      commit:
        required: false
        type: string
        description: Enter commit hash (use branch HEAD if not specified)

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          for i in singsaver moneyhero money101 comparehero moneyguru moneymax
          do
            echo "${{ github.event.inputs }}"
          done
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout commit
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "commit is ${{ github.event.inputs.commit }}"
          echo "ref is ${{ github.ref }}"
          echo "matrix is ${{fromJSON(needs.prepare.outputs.matrix)}}"